config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="my-3 mx-5">
  <h1>Edit flat</h1>
  <%= render "shared/form" %>
</div>

app/views/flats/index.html.erb
<%= render "shared/navbar" %>
<h1>All our flats (<%= @flats.length %>)</h1>
<div class="d-flex">
  <% @flats.each do |flat| %>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= flat.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= flat.address %></h6>
      <p class="card-text"><i class="fa-solid fa-users"></i> <%= flat.number_of_guests %> <i class="fa-solid fa-euro-sign"></i><%= flat.price_per_night %></p>
      <%= link_to "More info", flat_path(flat) %>
    </div>
  </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="my-3 mx-5">
  <h1>Add a new Flat</h1>
  <%= render "shared/form" %>
</div>

app/views/flats/show.html.erb
<%= render "shared/navbar" %>
<div class="d-flex row">
  <div class="col-9">
    <div>
      <h1><%= @flat.name %></h1>
      <p><%= @flat.address %></p>
    </div>
    <div>
      <h3>A bit more about this flat...</h3>
      <p><%= @flat.description %></p>
    </div>
    <div>
      <h3>Details</h3>
      <p><i class="fa-solid fa-users"></i> <%= @flat.number_of_guests %> <i class="fa-solid fa-euro-sign"></i><%= @flat.price_per_night %></p>
    </div>
  </div>
  <div class="col-3">
    <h3>Book this place</h3>
    <form>
      <div class="form-group">
        <p>From</p>
        <input type="text" class="form-control" placeholder="12/07/2026">
      </div>
      <div class="form-group">
        <p>To</p>
        <input type="text" class="form-control" placeholder="19/07/2026">
      </div>
      <div>
        <button type="submit" class="btn btn-primary">Book</button>
      </div>
    </form>
  </div>
</div>
<%= link_to "Back to flats", flats_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<%= simple_form_for [@flat] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :number_of_guests, as: :select, collection: (1..10).to_a %>
    <%= f.input :price_per_night %>
    <%= f.submit "Create flat", class: "btn btn-primary" %> <%= link_to "Cancel", flats_path, class: "btn btn-danger" %>
  <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">Simple Airbnb</span>
    <%= link_to "Add flat", new_flat_path, class: "btn btn-primary" %>
  </div>
</nav>